---
# Jeff Comer
# Ansible Playbook to create user and certificate for cert auth for all aci playbooks
# more recent galaxy collections have facilities to to this without json/aci_rest as shown below

- name: Create Certificat User
  hosts: apic
  connection: local
  gather_facts: False

  tasks:
#testing 123
    - name: TASK 01 - Create User
      cisco.aci.aci_aaa_user:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        aaa_user: ansible
        aaa_password: "{{ password }}"
        expiration: never
        expires: no
        state: "present"
      tags: aaa, certs

    - name: TASK 002 - Add Cert to User
      aci_aaa_user_certificate:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        aaa_user: ansible
        name: ansible
        certificate_name: ansible
        certificate_data: "{{ lookup('file', '../creds/ansible.crt') }}"
        validate_certs: False
      tags: aaa, certs


