---
# Jeff Comer
# Ansible Playbook to create user and certificate for cert auth for all aci playbooks
# more recent galaxy collections have facilities to to this without json/aci_rest as shown below

- name: Create Certificat User
  hosts: apic
  connection: local
  gather_facts: False

  tasks:
#testing 123
    - name: TASK 01 - Create User
      aci_rest:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        path: /api/mo/uni.json
        method: post
        content: {
          "aaaUser": {
              "attributes": {
                "accountStatus": "active",
                "clearPwdHistory": "yes",
                "dn": "uni/userext/user-ansible",
                "expiration": "never",
                "expires": "no",
                "name": "ansible",
                "pwdLifeTime": "no-password-expire",
                "status": "created,modified",
                "pwd": "DEVP@ssw0rd"
              },
              "children": [
                {
                  "aaaUserDomain": {
                    "attributes": {
                      "annotation": "",
                      "childAction": "",
                      "descr": "",
                      "name": "all",
                      "nameAlias": "",
                      "ownerKey": "",
                      "ownerTag": "",
                      "rn": "userdomain-all",
                      "status": "created,modified"
                    },
                    "children": [
                      {
                        "aaaUserRole": {
                          "attributes": {
                            "annotation": "",
                            "childAction": "",
                            "descr": "",
                            "name": "read-all",
                            "nameAlias": "",
                            "ownerKey": "",
                            "ownerTag": "",
                            "privType": "readPriv",
                            "rn": "role-read-all",
                            "status": "created,modified"
                          }
                        }
                      },
                      {
                        "aaaUserRole": {
                          "attributes": {
                            "annotation": "",
                            "descr": "",
                            "name": "admin",
                            "nameAlias": "",
                            "ownerKey": "",
                            "ownerTag": "",
                            "privType": "writePriv",
                            "rn": "role-admin",
                            "status": "created,modified"
                          }
                        }
                      }
                    ]
                  }
                }
              ]
            }
        }
      tags: aaa, certs

    - name: TASK 002 - Add Cert to User
      aci_aaa_user_certificate:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        aaa_user: ansible
        name: ansible
        certificate_name: ansible
        certificate_data: "{{ lookup('file', '../creds/ansible.crt') }}"
        validate_certs: False
      tags: aaa, certs


