---
# Jeff Comer
# Ansible Playbook to add hosts to vcenter and attach nic's to a DVS
# example seed file vars/<branch>/hx-hosts.yaml which was created using csv-to-yaml.py

- name: vCenter DVS Tasks
  hosts: localhost 
  connection: local
  gather_facts: False

  tasks:
    - read_csv:
        path: ../$varPath/vmware/hx-hosts.csv
      register: hostlist
      tags: hostadd, portgroup, vmotion

    - name: TASK - Enable SSH on all Hosts in the Cluster
      community.vmware.vmware_host_service_manager:
        hostname: "{{ vcsa_ipAddress }}"
        username: "{{ vcsa_user }}"
        password: "{{ vcsa_pwd }}"
        validate_certs: no
        cluster_name: "{{ cluster_name }}"
        service_name: TSM-SSH
        state: present
      delegate_to: localhost
      tags: ssh

    - name: TASK - Add vMotion Port Group to vSwitch
      community.vmware.vmware_portgroup:
        hostname: "{{ vcsa_ipAddress }}"
        username: "{{ vcsa_user }}"
        password: "{{ vcsa_pwd }}"
        validate_certs: no
        cluster_name: "{{ cluster_name }}"
        switch: "{{ hosts.vswitchName }}"
        portgroup: "{{ hosts.portGroupName }}"
        vlan_id: "{{ hosts.vlanId }}"
        state: present
      loop: "{{ hostlist.list }}"
      loop_control:
        loop_var: hosts
      delegate_to: localhost
      tags: portgroup

    - name: TASK - Add vMotion vmKernel to vSwitch
      community.vmware.vmware_vmkernel:
        hostname: "{{ vcsa_ipAddress }}"
        username: "{{ vcsa_user }}"
        password: "{{ vcsa_pwd }}"
        validate_certs: no
        esxi_hostname: "{{ hosts.host }}"
        vswitch_name: "{{ hosts.vswitchName }}"
        portgroup_name: "{{ hosts.portGroupName }}"
        enable_vmotion: True
        network:
          type: 'static'
          ip_address: "{{ hosts.vmotionIp }}"
          subnet_mask: "{{ hosts.vmotionNetMask }}"
          tcpip_stack: vmotion
        state: present
      loop: "{{ hostlist.list }}"
      loop_control:
        loop_var: hosts
      delegate_to: localhost
      tags: vmotion

    - name: TASK - Add Hosts to DVS 
      community.vmware.vmware_dvs_host:
        hostname: "{{ vcsa_ipAddress }}"
        username: "{{ vcsa_user }}"
        password: "{{ vcsa_pwd }}"
        validate_certs: no
        esxi_hostname: '{{ hosts.host }}'
        switch_name: HX-VMM
        vmnics:
            - vmnic10
            - vmnic11
        state: present
      loop: "{{ hostlist.list }}"
      loop_control:
        loop_var: hosts
      delegate_to: localhost
      tags: hostdvs

    - name: TASK - Add Links to LAG
      community.vmware.vmware_dvs_host:
        hostname: "{{ vcsa_ipAddress }}"
        username: "{{ vcsa_user }}"
        password: "{{ vcsa_pwd }}"
        validate_certs: no
        esxi_hostname: '{{ hosts.host }}'
        switch_name: HX-VMM
        lag_uplinks:
            - lag: HX-VMM-lacp
              vmnics:
                  - vmnic10
                  - vmnic11
        state: present
      loop: "{{ hostlist.list }}"
      loop_control:
        loop_var: hosts
      delegate_to: localhost
      tags: hostlag

