---
#Kelly Jones
#Ansible playbook to add devices to NSO

- hosts: localhost
  gather_facts: no

  tasks:
  - name: CREATE DEVICE IN NSO
    cisco.nso.nso_config:
      url: "{{ item.nsoUrl }}"
      username: ncsadmin
      password: ncsadmin
      data:
        tailf-ncs:devices:
          device:
           - address: "{{ item.c8000vAddress }}"
             description: CONFIGURED BY ANSIBLE!
             name: "{{ item.c8000vName }}"
             authgroup: "cl2022-rtrs"
             device-type:
               cli:
                 ned-id: "cisco-ios-cli-6.74"
             port: "22"
             state:
               admin-state: "unlocked"
    with_items: "{{ nsospecs }}"

  - name: Fetch ssh host keys
    cisco.nso.nso_action:
       url: "{{ item.nsoUrl }}"
       username: ncsadmin
       password: ncsadmin
       path: /ncs:devices/fetch-ssh-host-keys
       input: {}
    with_items: "{{ nsospecs }}"

  - name: Connect to Device
    cisco.nso.nso_action:
       url: "{{ item.nsoUrl }}"
       username: ncsadmin
       password: ncsadmin
       path: /ncs:devices/device{"{{ item.c8000vName }}"}/connect
       input: {}
    with_items: "{{ nsospecs }}"

  - name: Sync From Device
    cisco.nso.nso_action:
       url: "{{ item.nsoUrl }}"
       username: ncsadmin
       password: ncsadmin
       path: /ncs:devices/device{"{{ item.c8000vName }}"}/sync-from
       input: {}
    with_items: "{{ nsospecs }}"